services:
  template-script:
    build:
      context: ./template-script
      dockerfile: Dockerfile
    volumes:
      - ./template-script:/app
    working_dir: /app
    environment:
      - SCRIPT_ARG  # Dynamically set from the API
    command: ["sh", "-c", "bun run modified-index.ts \"$SCRIPT_ARG\""]
